require = ["stb", "tomlplusplus", "stb-image"]

[subprojects]
origami-core = { path = "../origami-core" }
origami-event = { path = "../origami-event" }
origami-window = { path = "../origami-window" }
origami-math = { path = "../origami-math" }
origami-assets = { path = "../origami-assets" }
origami-gfx = { path = "../origami-gfx" }

[project]
name = "origami-graphics"
version = "0.1.0"
description = ""
author = ""
email = ""
url = ""
license = ""

[compiler]
cxx = "g++"
standard = "c++20"
flags = []
includes = ["include"]
defines = []
warnings = []
debug = true

[compiler.windows]
includes = ["C:/VulkanSDK/1.3.275.0/Include"]

[linker]
type = "static-lib"
flags = []
libdirs = ["C:/VulkanSDK/1.3.275.0/Lib"]
libs = ["vulkan-1"]

[deps.stb]
git = "https://github.com/nothings/stb.git"
includes = ["./"]

[deps.tomlplusplus]
git = "https://github.com/marzer/tomlplusplus.git"
includes = ["include"]

[deps.stb-image]
git = "https://github.com/nothings/stb.git"
includes = ["./"]
