name = "origami-scene"
version = "0.1.0"
description = ""
author = ""
email = ""
url = ""
license = ""
requires = []

[subprojects]
origami-core = { path = "../origami-core" }
origami-event = { path = "../origami-event" }
origami-window = { path = "../origami-window" }
origami-math = { path = "../origami-math" }

[compiler]
cxx = "g++"
standard = "c++17"
flags = []
includes = ["include"]
defines = []
warnings = []
debug = true

[linker]
type = "static-lib"
flags = []
libdirs = []
libs = []
