name = "origami-gfx"
version = "0.1.0"
description = ""
author = ""
email = ""
url = ""
license = ""
require = []

[subprojects]
origami-core = { path = "../origami-core" }

[compiler]
cxx = "g++"
standard = "c++20"
flags = []
includes = ["include"]
defines = ["GLEW_STATIC"]
warnings = []
debug = true

[linker]
type = "static-lib"
flags = []
libdirs = []
libs = ["opengl32", "glu32"]
