require = []

[subprojects]
origami-core = { path = "../origami-core" }

[project]
name = "origami-gfx"
version = "0.1.0"
description = ""
author = ""
email = ""
url = ""
license = ""

[compiler]
cxx = "g++"
standard = "c++20"
flags = []
includes = ["include"]
defines = []
warnings = []
debug = true

[compiler.windows]
includes = ["C:/VulkanSDK/1.3.275.0/Include"]

[linker]
type = "static-lib"
flags = []
libdirs = ["C:/VulkanSDK/1.3.275.0/Lib"]
libs = ["vulkan-1"]
