
[metadata]
uuid = "53a1ef98-a9b5-9716-5bd6-4f26f97cb939"
type = "Graphics/Shader"
name = "Test Shader"

[info]
fragment = "assets/shaders/spirv/shader.frag.spv"
vertex = "assets/shaders/spirv/shader.vert.spv"
