name = "origami-utils"
version = "0.1.0"
description = ""
author = ""
email = ""
url = ""
license = ""
requires = []

[compiler]
cxx = "g++"
standard = "c++17"
flags = []
includes = ["include"]
defines = []
warnings = []
debug = true

[linker]
type = "static-lib"
flags = []
libdirs = []
libs = []
