require = ["tomlplusplus"]

[subprojects]
origami-core = { path = "../origami-core" }
origami-utils = { path = "../origami-utils" }

[project]
name = "origami-assets"
version = "0.1.0"
description = ""
author = ""
email = ""
url = ""
license = ""

[compiler]
cxx = "g++"
standard = "c++20"
flags = []
includes = ["include"]
defines = []
warnings = []
debug = true

[linker]
type = "static-lib"
flags = []
libdirs = []
libs = []

[deps.tomlplusplus]
git = "https://github.com/marzer/tomlplusplus.git"
includes = ["include"]
